name: Node.js CI

on:
  push:
    branches: [ anasofia ]
  pull_request:
    branches: [ anasofia ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] 

    env:
        EXPRESS_APP_MAP_API_KEY: ${{ secrets.EXPRESS_APP_MAP_API_KEY }}
        FRONT_END_DOMAIN: ${{ secrets.FRONT_END_DOMAIN }}
        GOOGLE_SHEETS_APIKEY: ${{ secrets.GOOGLE_SHEETS_APIKEY }}
        REACT_APP_BACKEND: ${{ secrets.REACT_APP_BACKEND }}
        REACT_APP_MAP_API_KEY: ${{ secrets.REACT_APP_MAP_API_KEY }}
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run: npm run install-dependencies
      
    - name: Run Tests
      run: |
        cd back-end
        npm test
      
    - name: Build Frontend
      run: |
        cd front-end
        npm run build

    - name: Build Backend
      run: |
        cd back-end
        npm run build